/**
 * 将 prisma/dev.db 编码为 base64，生成 TypeScript 文件。
 * 字符串常量一定会被打包器内联，比 JSON import 更可靠。
 */
const fs = require("fs");
const path = require("path");

const src = path.join(__dirname, "..", "prisma", "dev.db");
const dest = path.join(__dirname, "..", "lib", "db-base64.ts");

if (!fs.existsSync(src)) {
  console.warn("[embed-db] dev.db not found, skipping");
  process.exit(0);
}

const buffer = fs.readFileSync(src);
const base64 = buffer.toString("base64");

const content = `// Auto-generated by scripts/embed-db.cjs — DO NOT EDIT
export const DB_BASE64 = ${JSON.stringify(base64)};
`;

fs.writeFileSync(dest, content);
console.log(`[embed-db] wrote ${(buffer.length / 1024).toFixed(1)} KB → lib/db-base64.ts`);
