/**
 * 将 prisma/dev.db 编码为 base64 TS 文件。
 * Vercel 构建时执行，确保运行时数据库被包含在函数包中。
 */
const fs = require("fs");
const path = require("path");

const src = path.join(__dirname, "..", "prisma", "dev.db");
const dest = path.join(__dirname, "..", "lib", "db-base64.ts");

if (!fs.existsSync(src)) {
  console.warn("[embed-db] dev.db not found, skipping");
  process.exit(0);
}

const buffer = fs.readFileSync(src);
const base64 = buffer.toString("base64");

const content = `// Auto-generated by scripts/embed-db.cjs — DO NOT EDIT
export const DB_BASE64 = ${JSON.stringify(base64)};
export const DB_SIZE = ${buffer.length};
`;

fs.writeFileSync(dest, content, "utf-8");
console.log(`[embed-db] wrote ${(buffer.length / 1024).toFixed(1)} KB to lib/db-base64.ts`);
